language: python
python:
  - "3.5"
# command to install dependencies
install:
  - pip install codecov
  - pip install -e .[testing]
# command to run tests
script: py.test assignment_aa/tests.py
#codecov.io
after_success:
  - codecov
