language: python
python:
  - "2.6"
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"
# command to install dependencies
install:
  - pip install codecov
  - pip install -e .[testing]
# command to run tests
script: py.test --cov=./ assignment_aa/tests.py
#codecov.io
after_success:
  - codecov
